version: '3'
services:
  # 定时任务
  xxl-job-admin:
    container_name: geekai-xxl-job-admin
    image: registry.cn-shanghai.aliyuncs.com/yangjiacheng1996-geekai-plus/xxl-job-admin:2.4.0
    restart: always
    ports:
      - "8081:8080"
    environment:
      - PARAMS=--spring.config.location=/application.properties
    volumes:
      - ./logs:/data/applogs
      - ./application.properties:/application.properties
    networks:
      - geekai_plus_network

networks:
  geekai_plus_network:
    external: true