---
version: '3'
services:
  geekai-redis:
    image: registry.cn-shanghai.aliyuncs.com/yangjiacheng1996-geekai-plus/redis:6.0.6
    restart: always
    container_name: geekai-redis
    command: redis-server --requirepass 12345678
    volumes :
      - ./data:/data
    ports:
      - "6380:6379"
    networks:
      - geekai_plus_network

networks:
  geekai_plus_network:
    external: true