version: '3'
services:
# 前端应用
  geekai-web:
    image: registry.cn-shanghai.aliyuncs.com/yangjiacheng1996-geekai-plus/geekai-plus-web:v4.1.4-amd64
    container_name: geekai-web
    restart: always
    # depends_on:
    #   - geekai-api
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/var/log/nginx
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - geekai_plus_network

networks:
  geekai_plus_network:
    external: true